INC_DIRS := ../../include ../astar-bare
SRC_DIRS := ./ ../astar-bare
OBJ_DIR := ./obj
BIN_DIR := .
EXE_NAME := pp2d.out

include ../../makefile.rules

CXXFLAGS += -Wno-delete-non-virtual-dtor

# Uncomment the following lines for parallel execution
# CXXFLAGS += -fopenmp
# LDFLAGS += -fopenmp
